### PR TITLE
chg: 💄 rework the UI layout

### PR DESCRIPTION
**Pull request by AbdelfattahSekak**
This PR includes UI changes about the layout of visual elements.

### CODE REVIEW

**Comment by fg-mindee** [comment]
Mind sharing a small screenshot in the PR description @AbdelfattahSekak  please :pray:
So that we keep track of UI changes for each PR

**Review by charlesmindee — COMMENTED** [review]
Thanks for that @AbdelfattahSekak, could you please as mentioned FG add a screenshot of the demo to the PR so that we are aware of the changes as we are not familiar with react :) ?

**Comment by fg-mindee** [comment]
Mind pinging us here @AbdelfattahSekak when you're satisfied with your changes? :pray: (with one screenshot please)
I just saw that you pushed some changes, but we cannot know whether this is finalized :sweat_smile:

**Comment by AbdelfattahSekak** [comment]
Yes, I will let you know when it's done with a screenshot or better with the live demo deployed to better test the new UI.

**Comment by AbdelfattahSekak** [comment]
I need to merge this PR to make a new deployment. Here is how the interface looks like now. 

Screenshot from 2022-01-06 13-20-41

**Review by fg-mindee — COMMENTED** [review]
Looking really good, an impressive job @AbdelfattahSekak :clap: 

I wasn't involved enough for my review to count, so I'll let @charlesmindee approve :+1:

**Review by charlesmindee — APPROVED** [review]
Thanks!

**Pull request merged**
