### PR TITLE
chg: 🔥 remove ResNet model

### PR DESCRIPTION
**Pull request by AbdelfattahSekak**
This PR should remove the ResNet modal from the demo.

### CODE REVIEW

**Review by fg-mindee — COMMENTED** [review]
Thanks! Since I'm not the one who spent the most time with this, I think it's better to wait for @charlesmindee review as well :+1:

**Comment by AbdelfattahSekak** [comment]
@charlesmindee Can you please check this one ? :pray:

**Review by charlesmindee — APPROVED** [review]
Thanks for that !

**Comment by fg-mindee** [comment]
@AbdelfattahSekak don't forget to delete branches once the PR is merged :point_up: :)

**Pull request merged**
